name: CI

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-18.04
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository)
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install nasm

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Configure
      run: ./configure --enable-libxml2

    - name: Build
      run: make -j 8

    - name: Check
      run: make check -j 8
