name: CI

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-18.04
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository)
    steps:
    - name: Install dependencies
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository -y "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-12 main"
        sudo apt update -q
        sudo apt install -y clang-format-12
        sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-12 1000
        sudo apt install -y nasm

    - name: Checkout
      uses: actions/checkout@v2

    - name: Checkout Fate
      uses: actions/checkout@v2
      if: github.ref == 'refs/heads/develop'
      with:
        repository: sandflow/ffmpeg-imf-fate
        path: ./fate-suite
        token: ${{ secrets.GITHUBPAT }}
        persist-credentials: true
        ref: 6482e3fb12fe9fbfe4ceb8ecdb1774ac853408c5

    - name: Check code style
      run: |
        ./imf-check-style.sh

    - name: Configure
      run: ./configure --enable-libxml2

    - name: Build
      run: make -j 8

    - name: Basic unit tests
      if: github.ref != 'refs/heads/develop'
      run: |
        ./imf-unit-tests.sh

    - name: Run Fate
      if: github.ref == 'refs/heads/develop'
      run: |
        FATE_SAMPLES=fate-suite/ make fate
