name: CI

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-18.04
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository)
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install indent nasm

    - name: Checkout
      uses: actions/checkout@v2

    - name: Checkout Fate
      uses: actions/checkout@v2
      if: github.ref == 'refs/heads/develop'
      with:
        repository: sandflow/ffmpeg-imf-fate
        path: ./fate-suite
        token: ${{ secrets.GITHUBPAT }}
        persist-credentials: true
        ref: 6482e3fb12fe9fbfe4ceb8ecdb1774ac853408c5

    - name: Configure
      run: ./configure --enable-libxml2

    - name: Check code style
      run: indent -i4 -kr -nut libavformat/imf*.c

    - name: Build
      run: make -j 8

    - name: Check
      run: make check -j 8

    - name: Run Fate
      if: github.ref == 'refs/heads/develop'
      run: FATE_SAMPLES=fate-suite/ make fate
